version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/budget-tracker
      - JWT_SECRET=your_jwt_secret_key_here
    depends_on:
      - mongodb
    volumes:
      - ./user-service:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
